### ISSUE TITLE
Missing file VERSION for source installation from PyPI

### ISSUE THREAD

**Issue by jayqi** [saturncloud/dask-pytorch#4]
When doing an install from source from PyPI, the installation fails because the `VERSION` file is missing:

```
❯ pip install dask-pytorch --no-binary :all:
Collecting dask-pytorch
  Downloading dask-pytorch-0.1.0.tar.gz (8.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/jqi/miniconda3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nq/vp3dgt812jgb0q09rh5l706c0000gn/T/pip-install-lwhzmu1h/dask-pytorch/setup.py'"'"'; __file__='"'"'/private/var/folders/nq/vp3dgt812jgb0q09rh5l706c0000gn/T/pip-install-lwhzmu1h/dask-pytorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/nq/vp3dgt812jgb0q09rh5l706c0000gn/T/pip-pip-egg-info-_i2ttudx
         cwd: /private/var/folders/nq/vp3dgt812jgb0q09rh5l706c0000gn/T/pip-install-lwhzmu1h/dask-pytorch/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nq/vp3dgt812jgb0q09rh5l706c0000gn/T/pip-install-lwhzmu1h/dask-pytorch/setup.py", line 7, in <module>
        with open("VERSION", "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This won't be a problem for most users because `pip` will install from the wheel distribution, but in some cases the wheel won't work and pip will fall back to unpacking the tar archive and installing from source. You can download the tar archive manually and see that indeed the `VERSION` file is missing. 

`VERSION` is a nonstandard file for `setup.py` builds, so you'll need to create a `MANIFEST.in` file that explicitly includes it. https://packaging.python.org/guides/using-manifest-in/

**Comment by jameslamb** [comment]
Thanks @jayqi !

I can add this and add a test that installs from the tarball produced by `python setup.py sdist` so we catch other issues with non-wheel installs in the future.
